@startuml
hide empty circle
hide empty members
skinparam shadowing false
"核心" <|-- "支付前置"
"IC卡系统" <|-- "支付前置"
"兴业银银平台" <|-- "支付前置"
"银联、网联、农信银" <|-- "支付前置"
"密码服务平台" <|-- "支付前置"
"统一认证" <|-- "支付前置"
"消息平台" <|-- "支付前置"
"核心" <|-- "统一支付"
"支付前置" <|-- "统一支付"
"核心" <|-- "后督"
"柜面无纸化" <|-- "后督"
"影像平台" <|-- "后督"
"档案系统" <|-- "后督"
"银联前置" <|-- "IC卡系统"
"ATMP" <|-- "IC卡系统"
"柜台" <|-- "IC卡系统"
"密码服务平台" <|-- "IC卡系统"
"统一支付" <|-- "统一查控"
"核心" <|-- "统一查控"
"电信反欺诈前置" <|-- "统一查控"
"影像平台" <|-- "无纸化系统"
"后督系统" <|-- "无纸化系统"
"电子签章系统" <|-- "无纸化系统"
"旧核心" <|-- "加密平台"
"旧IC卡系统" <|-- "加密平台"
"旧发卡系统" <|-- "加密平台"
"2台签名硬件" <|-- "加密平台"
"核心" <|-- "ATMP"
"统一支付" <|-- "ATMP"
"消息平台" <|-- "ATMP"
"IC卡系统" <|-- "ATMP"
"互金平台" <|-- "ATMP"
"影像平台" <|-- "ATMP"
"统一认证" <|-- "ATMP"
"密码服务平台" <|-- "ATMP"
"密码服务平台" <|-- "柜面系统"
"IC卡系统" <|-- "柜面系统"
"统一支付" <|-- "柜面系统"
"影像平台" <|-- "柜面系统"
"后督系统" <|-- "柜面系统"
"统一认证" <|-- "柜面系统"
"消息平台" <|-- "柜面系统"
"电子签章系统" <|-- "柜面系统"
"中间业务平台" <|-- "柜面系统"
"电子银行" <|-- "柜面系统"
"无纸化系统" <|-- "柜面系统"
"电子验印系统" <|-- "柜面系统"
"反洗钱" <|-- "柜面系统"
"统一查控" <|-- "柜面系统"
"智能网点" <|-- "柜面系统"
"账户管理系统" <|-- "柜面系统"
"核心" <|-- "柜面系统"
"外设" <|-- "柜面系统"
"核心" <|-- "中间业务平台"
"统一支付" <|-- "中间业务平台"
"统一认证" <|-- "中间业务平台"
"消息平台" <|-- "中间业务平台"
"兴业数金托管系统" <|-- "中间业务平台"
"密码服务平台" <|-- "统一认证"
"OA、KK" <|-- "统一认证"
"互金平台、ESB、核心系统等兴业托管系统" <|-- "消息平台"
"核心系统or大数据平台" <|-- "反洗钱"
"名单管理系统" <|-- "反洗钱"
"统一查控" <|-- "反洗钱"
"核心" <|-- "财务系统"
"统一认证" <|-- "财务系统"
"OA系统" <|-- "财务系统"
"信贷系统" <|-- "财务系统"
"统一支付" <|-- "财务系统"
"影像平台" <|-- "财务系统"
"档案系统" <|-- "财务系统"
"税控系统" <|-- "财务系统"
"第三方商旅平台" <|-- "财务系统"
"--" <|-- "税控系统"
"互金平台" <|-- "客服系统"
"密码服务平台" <|-- "客服系统"
"统一认证" <|-- "客服系统"
"统一支付" <|-- "客服系统"
"消息平台" <|-- "客服系统"
"电子银行" <|-- "客服系统"
"核心" <|-- "客服系统"
"征信前置查询" <|-- "综合信贷"
"影像平台" <|-- "综合信贷"
"核心" <|-- "综合信贷"
"综合信贷" <|-- "征信报送"
"无" <|-- "征信查询"
"核心" <|-- "减估值"
"综合报表系统" <|-- "减估值"
"核心" <|-- "新电子银行"
"影像平台" <|-- "新电子银行"
"统一认证" <|-- "新电子银行"
"消息平台" <|-- "新电子银行"
"密码服务平台" <|-- "新电子银行"
"电子签章系统" <|-- "新电子银行"
"统一支付" <|-- "新电子银行"
"中间业务平台" <|-- "新电子银行"
"ATMP" <|-- "新电子银行"
"互金平台" <|-- "新电子银行"
"票据系统" <|-- "新电子银行"
"数据中台" <|-- "新电子银行"
"反欺诈" <|-- "新电子银行"
"客服系统" <|-- "新电子银行"
"核心" <|-- "数据中台"
"核心" <|-- "互金"
"互金平台" <|-- "网贷系统"
"电子合同系统" <|-- "网贷系统"
"第三方征信数据厂商" <|-- "网贷系统"
"身份核验系统" <|-- "网贷系统"
"OCR识别系统" <|-- "网贷系统"
"活体验证系统" <|-- "网贷系统"
"核心" <|-- "数字银行"
"统一认证" <|-- "数字银行"
"密码服务平台" <|-- "数字银行"
"消息平台" <|-- "数字银行"
"统一支付" <|-- "数字银行"
"影像平台" <|-- "数字银行"
"互金平台" <|-- "数字银行"
"互金平台" <|-- "供应链金融服务平台"
"网贷平台" <|-- "供应链金融服务平台"
"消息平台" <|-- "供应链金融服务平台"
"核心" <|-- "供应链金融服务平台"
"统一认证" <|-- "智能网点"
"密码服务平台" <|-- "智能网点"
"消息平台" <|-- "智能网点"
"影像平台" <|-- "智能网点"
"互金平台" <|-- "智能网点"
"IC卡系统" <|-- "智能网点"
"核心" <|-- "智能网点"
"核心" <|-- "票据系统"
"综合报表系统" <|-- "票据系统"
"监管报送" <|-- "票据系统"
"股权关联关系" <|-- "票据系统"
"减估值系统" <|-- "票据系统"
"电子银行" <|-- "票据系统"
"密码服务平台" <|-- "票据系统"
"统一认证" <|-- "票据系统"
"消息平台" <|-- "票据系统"
"综合信贷" <|-- "票据系统"
"核心" <|-- "资金业务管理系统"
"综合信贷" <|-- "资金业务管理系统"
"综合报表系统" <|-- "资金业务管理系统"
"监管报送" <|-- "资金业务管理系统"
"股权关联关系" <|-- "资金业务管理系统"
"核心or数据中台" <|-- "资金内部转移定价系统"
"核心or数据中台" <|-- "统一监管报送（含个人结算账户报送、全国集中账户报送）"
"核心or数据中台" <|-- "综合报表系统"
"数字银行" <|-- "交易反欺诈"
"互金平台" <|-- "交易反欺诈"
"统一支付" <|-- "交易反欺诈"
"电子银行" <|-- "交易反欺诈"
"消息平台" <|-- "交易反欺诈"
@enduml